name: 'Build Aurora Corne'
on: 
  - push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left","splitkb_aurora_corne_right"]'

      # mouse keys setup
      # https://github.com/manna-harbour/miryoku_zmk/blob/master/.github/workflows/build-example-mousekeyspr.yml
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll", "zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
      
      alphas: '["qwerty"]'
      tap: '["qwerty"]'
      extra: '["colemakdh"]'
      # nav: '["vi"]'
