name: 'Build Aurora Corne'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left","splitkb_aurora_corne_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      branches: '["caksoylar/zmk/feat/mouse-keys-3.2"]'
      # branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2 caksoylar/zmk/feat/mouse-keys-3.2"]'
