name: 'Build Aurora Corne'
on: 
  - push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left","splitkb_aurora_corne_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      branches: '["zmkfirmware/zmk/main", "caksoylar/zmk/feat/mouse-keys-3.2"]'
      
      alphas: '["qwerty"]'
      tap: '["qwerty"]'
      extra: '["colemakdh"]'
      # nav: '["vi"]'
